# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

template: |
  <!-- Optional: add a release summary here -->
  $CHANGES

# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: ":boom: Breaking changes"
    labels: 
      - breaking
  - title: 🚨 Removed
    label: removed
  - title: ":tada: Major features and improvements"
    labels:
      - major-enhancement
  - title: ⚠️ Deprecated
    label: deprecated
  - title: 🚀 New features and improvements
    labels:
      - enhancement
      - feature
  - title: 🐛 Bug Fixes
    labels:
      - bug
      - fix
      - bugfix
      - regression
  # Default label used by Dependabot
  - title: 📦 Dependency updates
    label: dependencies
  - title: 📝 Documentation updates
    label: documentation
  - title: 🧰 Maintenance
    labels: 
      - chore
      - internal
  - title: 🚦 Tests
    labels: 
      - test
      - tests

exclude-labels:
  - reverted
  - no-changelog
  - skip-changelog
  - invalid

change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
version-resolver:
  major:
    labels:
      - breaking
  minor:
    labels:
      - feature
      - major-enhancement
  patch:
    labels:
      - patch
  default: patch

autolabeler:
  - label: 'documentation'
    files:
      - 'doc.go'
    branch:
      - '/docs{0,1}\/.+/'
      - '/documentation\/.+/'
  - label: 'chore'
    files:
      - '*.md'
    branch:
      - '/chore\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
    body:
      - '/JIRA-[0-9]{1,4}/'
